name: Strapi Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change Directory
        run: cd /home/ubuntu/strapi-terraform
        
      - name: Git Pull 
        run: git pull

      - name: Run Strapi
        run: pm2 restart strapi
